# Generated by Django 5.0.6 on 2024-05-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('speciality', models.CharField(blank=True, max_length=256, null=True)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('online_status', models.BooleanField()),
                ('last_activity', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_status', models.BooleanField()),
                ('confirmation_of_payment', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('last_activity', models.DateTimeField()),
            ],
        ),
    ]
